### ISSUE TITLE
Incompatible with DeluxeChat ?

### ISSUE THREAD

**Issue by dgentile24** [strumswell/ServerlistMOTD-X#4] opened 2020-03-17 09:14 UTC
Hi, as mentioned on bukkit there is an incompatibility with DeluxeChat, it does in fact stop DeluxeChat from modifying the chat as it should. Here are the informations you asked for:

Server version: Spigot 1.13.2
DeluxeChat: 1.15.0
ProtocolLib: 4.5.0
Vault: 1.7.2
Your plugin: 2020-03-02

And there are no errors, I don't really understand why it doesn't work x)
(Pretty much all the latest versions except for Spigot)

**Comment by strumswell** [comment] 2020-03-17 09:43
Do you have the same problem with X-2018-10-20? I disregarded the chat functions in my vault integration in 2020-03-02 because they don't matter in a serverlist plugin. This could have broken your DeluxeChat functionality. Super weird that this could have influenced the functionality of a third party.

**Comment by strumswell** [comment] 2020-03-17 10:37
I tried to recreate your bug with ChatControl (because DeluxeChat is paid) **without any luck**. 

Spigot: 1.13.2
ChatControl: 5.8.7 (Formatter: Enabled: true ->  Message_Format: '&b{player}:&c {message}')
Essentials: 2.17.2.0 (change-displayname: false in config.yml)
ProtocolLib: 4.3.0
Vault: v1.7.2-b107

**The chat was being modified as intended** (see screenshot)

<img width="966" alt="Bildschirmfoto 2020-03-17 um 11 30 48" src="https://user-images.githubusercontent.com/6720421/76847702-c3c7c180-6842-11ea-88e4-af814eee9b91.png">

So I suspect **three possible errors** on your side:
- DeluxeChat is buggy or doesn't tap into Vault
- Misconfigured DeluxeChat config
- Some other plugin intervenes into the chat (see Essentials change-displayname: false in config.yml)

If you still think ServerlistMOTD introduced the problem, **please give me some more information** like what exactly can't DeluxeChat modify in your chat or some other hints that maybe useful.

**Comment by dgentile24** [comment] 2020-03-17 11:01
Mmh that's pretty strange cause when I remove ServerListMOTD all works just fine and it does hook into vault but I don't know why it doesn't work. Going to try the thing about essentials but I don't think it's that cause it works well without the ServerListMOTD. Do you want a copy of the plugin for debug purposes ?

**Comment by strumswell** [comment] 2020-03-17 11:07
That would be very helpful, you can send it to me via philipp@bolte.cloud.

Can you also send me a full server log and can you try running your server without vault? Just an idea.

**Comment by dgentile24** [comment] 2020-03-17 11:34
Here are the logs (I also sent you the email with the plugin)
[withvault.log](https://github.com/strumswell/ServerlistMOTD-X/files/4343195/withvault.log)
[withoutvault.log](https://github.com/strumswell/ServerlistMOTD-X/files/4343196/withoutvault.log)

**Comment by strumswell** [comment] 2020-03-17 11:41
Hm, very weird. I'm very busy atm so give me some time to work on it. In the meantime, can you try this older version of ServerlistMOTD (pre-vault adjustment) https://github.com/strumswell/ServerlistMOTD-X/releases/tag/X-2018-10-20
Maybe this helps?

**Comment by dgentile24** [comment] 2020-03-17 11:46
Doesn't work either with the older version of the plugin, really weird...

**Comment by strumswell** [comment] 2020-03-17 12:48
Update - I got everything working by doing the following:
1. Install DeluxeChat
2. Install a permissions plugin (LuckPerms in this case)
3. Install ServerlistMOTD, Vault, Eco Plugin, ProtocolLib, PlaceholderAPI
4. Configure DeluxeChat config (group default or add another group)
5. Start Server
6. Install PlaceholderAPI-Extensions for Player, Vault and DeluxeChat
6.1 /papi ecloud download player 
6.2 /papi ecloud download vault 
6.3 /papi ecloud download DeluxeChat
6.4 /papi reload
7. Add permissions of DeluxeChat format group to user or permission group
7.1 /lp user Strumswell permission set chatformat.default

After that, you should see everything formatted. Worked on my site (see screenshot)
<img width="1035" alt="Bildschirmfoto 2020-03-17 um 13 46 09" src="https://user-images.githubusercontent.com/6720421/76857423-b1a34e80-6855-11ea-85b6-1af2a44595ee.png">

My DeluxeChat config.yml
```iml
# DeluxeChat version 1.15.0 config file
# Created by extended_clip
# List as many format configurations you in the formats: config section.
# Each format configuration requires a specific layout which can be seen below.
# Format priority must be specified per format and each priority must be unique.
# higher value = lower priority
# ex: guest-100, owner-1
#   YOU MUST KEEP A 'default' TEMPLATE! 
#   
# Social Spy only allows %player% and %recipient% as placeholders
# 
# You must download the placeholder expansion through PlaceholderAPI for which
# placeholders you want to use. The example below uses Player placeholders, so
# we need to download the player expansion: /papi ecloud download Player, /papi reload
# 
# 
# example format template:
# formats: 
#   default:
#     priority: 2147483647
#     channel: ''
#     prefix: '&8[&7Guest&8] '
#     name_color: '&7'
#     name: '%player_name%'
#     suffix: '&7> '
#     chat_color: '&f'
#     channel_tooltip:
#     - '&7%player_name% &bis a Guest'
#     prefix_tooltip:
#     - '&7%player_name% &bis a Guest'
#     name_tooltip:
#     - ''
#     suffix_tooltip:
#     - ''
#     channel_click_command: '
#     prefix_click_command: '/ranks
#     name_click_command: '/msg %player_name% 
#     suffix_click_command: '
#   Member:
#     priority: 100
#     channel: ''
#     prefix: '&8[&aMember&8] '
#     name_color: '&7'
#     name: '%player_name%'
#     suffix: '&7> '
#     chat_color: '&f'
#     channel_tooltip:
#     - '&7%player_name% &bis a Member'
#     prefix_tooltip:
#     - '&7%player_name% &bis a Member'
#     name_tooltip:
#     - ''
#     suffix_tooltip:
#     - ''
#     channel_click_command: '
#     prefix_click_command: '/ranks
#     name_click_command: '/msg %player_name% 
#     suffix_click_command: '
check_updates: true
relation_placeholders_enabled: true
timestamp_format: MM/dd/yy HH:mm:ss
boolean:
  'true': '&atrue'
  'false': '&cfalse'
ops_use_group_format: false
chat_filter:
  enabled: false
  ignore_case: true
  list:
  - '.; '
  - fuck;fuck
private_message:
  enabled: true
  bungeecord: false
private_message_formats:
  to_sender:
    format: '&7you &e-> &7%recipient_player_name% &7:'
    tooltip:
    - '%player_name%'
    click_command: '/r '
    chat_color: '&f'
  to_recipient:
    format: '&7%player_name% &e-> &7you &7:'
    tooltip:
    - '%player_name%'
    click_command: '/r '
    chat_color: '&f'
  social_spy: '&8[&cspy&8] &f%player% &e-> &f%recipient%&7:'
formats:
  default:
    priority: 2147483647
    channel: ''
    prefix: '&8[&7Guest&8] '
    name_color: ''
    name: '&7%player_name%'
    suffix: ' &7&l» '
    chat_color: '&f'
    channel_tooltip:
    - '&c%player%s &7custom tag'
    - '%deluxetags_description%'
    prefix_tooltip: []
    name_tooltip:
    - '&7-=[&6✦&7]=-  &7-=[&e%player_name%&7]=-  &7-=[&6✦&7]=-'
    - '&5Sent: &f%player_timestamp%'
    - '&eStatus: &f%deluxestatus_status%'
    - '&cCurrent rank: %ezrankslite_rankprefix%'
    - '&cNext rank: %ezrankslite_nextrankprefix%'
    - '&cRankup progress: %ezrankslite_progressbar%'
    - '&cCurrent prestige: %ezprestige_prestigetag%'
    - '&6Blocks broken&7: &f%ezblocks_broken% blocks'
    - '&eEnchant Tokens&7: &f%tokenenchant_tokens%'
    - '&aBalance&7: &a$&f%ezrankslite_balance%'
    - '&aChatReaction wins&7: &f%chatreaction_wins%'
    - '&bServer: &f%player_server%'
    suffix_tooltip: []
    channel_click_command: '[URL]http://www.spigotmc.org/resources/deluxetags.4390/'
    prefix_click_command: '[EXECUTE]/ranks'
    name_click_command: /ranks
    suffix_click_command: ''
  Owner:
    priority: 1
    channel: ''
    prefix: '&2[&aOwner&2] '
    name_color: '&a'
    name: '%player_name%'
    suffix: ' &7&l» '
    chat_color: '&b'
    channel_tooltip:
    - '&c%player%s &7custom tag'
    - '%deluxetags_description%'
    prefix_tooltip: []
    name_tooltip:
    - '&7-=[&6✦&7]=-  &7-=[&e%player_name%&7]=-  &7-=[&6✦&7]=-'
    - '&5Sent: &f%player_timestamp%'
    - '&eStatus: &f%deluxestatus_status%'
    - '&cCurrent rank: %ezrankslite_rankprefix%'
    - '&cNext rank: %ezrankslite_nextrankprefix%'
    - '&cRankup progress: %ezrankslite_progressbar%'
    - '&cCurrent prestige: %ezprestige_prestigetag%'
    - '&6Blocks broken&7: &f%ezblocks_broken% blocks'
    - '&eEnchant Tokens&7: &f%tokenenchant_tokens%'
    - '&aBalance&7: &a$&f%ezrankslite_balance%'
    - '&aChatReaction wins&7: &f%chatreaction_wins%'
    - '&bServer: &f%player_server%'
    suffix_tooltip: []
    channel_click_command: '[URL]http://www.spigotmc.org/resources/deluxetags.4390/'
    prefix_click_command: '[EXECUTE]/ranks'
    name_click_command: /ranks
    suffix_click_command: ''
bungeecord:
  enabled: false
  server_name: Server
  server_prefix: '&8[&cServer&8]'
  join_global: true
  use_server_whitelist: true
  server_whitelist:
  - Server2
  - Server3
```

**Comment by dgentile24** [comment] 2020-03-17 20:41
Hey,
I tried doing what you did and it does Indeed works. But you know what ? I tested all my plugins to know which one was causing that and the answer was « none » yes, none, in fact, when you hit the 49 plugins in the same server, DeluxeChat seem to stop working :’D I don’t know why but hey I mean ok :’D what’s Strange is that when I remove your plugin and replace it with an other ServerlistMOTD plugin it does work properly with 49+ plugins very weird :/

De : Philipp Bolte<mailto:notifications@github.com>
Envoyé le :mardi 17 mars 2020 13:49
À : strumswell/ServerlistMOTD-X<mailto:ServerlistMOTD-X@noreply.github.com>
Cc : Gentile Donato<mailto:donato.gentile@student.unamur.be>; Author<mailto:author@noreply.github.com>
Objet :Re: [strumswell/ServerlistMOTD-X] Incompatible with DeluxeChat ? (#4)


Update - I got everything working by doing the following:

  1.  Install DeluxeChat
  2.  Install a permissions plugin (LuckPerms in this case)
  3.  Install ServerlistMOTD, Vault, Eco Plugin, ProtocolLib, PlaceholderAPI
  4.  Configure DeluxeChat config (group default or add another group)
  5.  Start Server
  6.  Install PlaceholderAPI-Extensions for Player, Vault and DeluxeChat
6.1 /papi ecloud download player
6.2 /papi ecloud download vault
6.3 /papi ecloud download DeluxeChat
6.4 /papi reload
  7.  Add permissions of DeluxeChat format group to user or permission group
7.1 /lp user Strumswell permission set chatformat.default

After that, you should see everything formatted. Worked on my site (see screenshot)
[Bildschirmfoto 2020-03-17 um 13 46 09]<https://user-images.githubusercontent.com/6720421/76857423-b1a34e80-6855-11ea-85b6-1af2a44595ee.png>

My DeluxeChat config.yml

# DeluxeChat version 1.15.0 config file



# Created by extended_clip



# List as many format configurations you in the formats: config section.



# Each format configuration requires a specific layout which can be seen below.



# Format priority must be specified per format and each priority must be unique.



# higher value = lower priority



# ex: guest-100, owner-1



#   YOU MUST KEEP A 'default' TEMPLATE!



#



# Social Spy only allows %player% and %recipient% as placeholders



#



# You must download the placeholder expansion through PlaceholderAPI for which



# placeholders you want to use. The example below uses Player placeholders, so



# we need to download the player expansion: /papi ecloud download Player, /papi reload



#



#



# example format template:



# formats:



#   default:



#     priority: 2147483647



#     channel: ''



#     prefix: '&8[&7Guest&8] '



#     name_color: '&7'



#     name: '%player_name%'



#     suffix: '&7> '



#     chat_color: '&f'



#     channel_tooltip:



#     - '&7%player_name% &bis a Guest'



#     prefix_tooltip:



#     - '&7%player_name% &bis a Guest'



#     name_tooltip:



#     - ''



#     suffix_tooltip:



#     - ''



#     channel_click_command: '



#     prefix_click_command: '/ranks



#     name_click_command: '/msg %player_name%



#     suffix_click_command: '



#   Member:



#     priority: 100



#     channel: ''



#     prefix: '&8[&aMember&8] '



#     name_color: '&7'



#     name: '%player_name%'



#     suffix: '&7> '



#     chat_color: '&f'



#     channel_tooltip:



#     - '&7%player_name% &bis a Member'



#     prefix_tooltip:



#     - '&7%player_name% &bis a Member'



#     name_tooltip:



#     - ''



#     suffix_tooltip:



#     - ''



#     channel_click_command: '



#     prefix_click_command: '/ranks



#     name_click_command: '/msg %player_name%



#     suffix_click_command: '



check_updates: true



relation_placeholders_enabled: true



timestamp_format: MM/dd/yy HH:mm:ss



boolean:



  'true': '&atrue'



  'false': '&cfalse'



ops_use_group_format: false



chat_filter:



  enabled: false



  ignore_case: true



  list:



  - '.; '



  - fuck;fuck



private_message:



  enabled: true



  bungeecord: false



private_message_formats:



  to_sender:



    format: '&7you &e-> &7%recipient_player_name% &7:'



    tooltip:



    - '%player_name%'



    click_command: '/r '



    chat_color: '&f'



  to_recipient:



    format: '&7%player_name% &e-> &7you &7:'



    tooltip:



    - '%player_name%'



    click_command: '/r '



    chat_color: '&f'



  social_spy: '&8[&cspy&8] &f%player% &e-> &f%recipient%&7:'



formats:



  default:



    priority: 2147483647



    channel: ''



    prefix: '&8[&7Guest&8] '



    name_color: ''



    name: '&7%player_name%'



    suffix: ' &7&l» '



    chat_color: '&f'



    channel_tooltip:



    - '&c%player%s &7custom tag'



    - '%deluxetags_description%'



    prefix_tooltip: []



    name_tooltip:



    - '&7-=[&6✦&7]=-  &7-=[&e%player_name%&7]=-  &7-=[&6✦&7]=-'



    - '&5Sent: &f%player_timestamp%'



    - '&eStatus: &f%deluxestatus_status%'



    - '&cCurrent rank: %ezrankslite_rankprefix%'



    - '&cNext rank: %ezrankslite_nextrankprefix%'



    - '&cRankup progress: %ezrankslite_progressbar%'



    - '&cCurrent prestige: %ezprestige_prestigetag%'



    - '&6Blocks broken&7: &f%ezblocks_broken% blocks'



    - '&eEnchant Tokens&7: &f%tokenenchant_tokens%'



    - '&aBalance&7: &a$&f%ezrankslite_balance%'



    - '&aChatReaction wins&7: &f%chatreaction_wins%'



    - '&bServer: &f%player_server%'



    suffix_tooltip: []



    channel_click_command: '[URL]http://www.spigotmc.org/resources/deluxetags.4390/'



    prefix_click_command: '[EXECUTE]/ranks'



    name_click_command: /ranks



    suffix_click_command: ''



  Owner:



    priority: 1



    channel: ''



    prefix: '&2[&aOwner&2] '



    name_color: '&a'



    name: '%player_name%'



    suffix: ' &7&l» '



    chat_color: '&b'



    channel_tooltip:



    - '&c%player%s &7custom tag'



    - '%deluxetags_description%'



    prefix_tooltip: []



    name_tooltip:



    - '&7-=[&6✦&7]=-  &7-=[&e%player_name%&7]=-  &7-=[&6✦&7]=-'



    - '&5Sent: &f%player_timestamp%'



    - '&eStatus: &f%deluxestatus_status%'



    - '&cCurrent rank: %ezrankslite_rankprefix%'



    - '&cNext rank: %ezrankslite_nextrankprefix%'



    - '&cRankup progress: %ezrankslite_progressbar%'



    - '&cCurrent prestige: %ezprestige_prestigetag%'



    - '&6Blocks broken&7: &f%ezblocks_broken% blocks'



    - '&eEnchant Tokens&7: &f%tokenenchant_tokens%'



    - '&aBalance&7: &a$&f%ezrankslite_balance%'



    - '&aChatReaction wins&7: &f%chatreaction_wins%'



    - '&bServer: &f%player_server%'



    suffix_tooltip: []



    channel_click_command: '[URL]http://www.spigotmc.org/resources/deluxetags.4390/'



    prefix_click_command: '[EXECUTE]/ranks'



    name_click_command: /ranks



    suffix_click_command: ''



bungeecord:



  enabled: false



  server_name: Server



  server_prefix: '&8[&cServer&8]'



  join_global: true



  use_server_whitelist: true



  server_whitelist:



  - Server2



  - Server3

**Comment by dgentile24** [comment] 2020-03-17 20:45
Hey,
I tried doing what you did and it does Indeed works. But you know what ? I tested all my plugins to know which one was causing that and the answer was « none » yes, none, in fact, when you hit the 49 plugins in the same server, DeluxeChat seem to stop working :’D I don’t know why but hey I mean ok :’D what’s Strange is that when I remove your plugin and replace it with an other ServerlistMOTD plugin it does work properly with 49+ plugins very weird :/

**Comment by strumswell** [comment] 2020-03-17 22:01
That must be some very specific low level problem which would be very difficult to identify. Can we close the issue or do you have more info on the described behaviour?

**Comment by dgentile24** [comment] 2020-03-17 22:35
Yes we can close this issue, don't think that we will able to identify the problem :/

**Closed** 2020-03-17 22:36 UTC
Labels: bug
